# Generated by Django 4.2.1 on 2023-06-02 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_user_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="base_ptr",
        ),
        migrations.DeleteModel(
            name="Base",
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
