# Generated by Django 4.2.3 on 2023-07-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_user_debt_amount_user_document_user_document_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='person_type',
            field=models.CharField(blank=True, choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], max_length=2, null=True),
        ),
    ]
